# Generated by Django 5.2.7 on 2025-11-01 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cameras', '0002_camera_viewers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(help_text='Unique device identifier (e.g., MAC address, UUID, or serial)', max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('protocol', models.CharField(default='websocket', help_text='Communication protocol, currently fixed to WebSocket', max_length=20)),
                ('device_token', models.CharField(editable=False, help_text='Random token generated at registration for WebSocket auth', max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict, help_text='Dynamic nested data structure (e.g., sensor readings, states)')),
                ('schema', models.JSONField(default=dict, help_text='UI + control definitions for frontend rendering')),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False, help_text='Live WebSocket status')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_payload_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHasCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as main display camera if needed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Camera order in display or monitoring sequence')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_links', to='Applications.application')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_links', to='Cameras.camera')),
            ],
            options={
                'verbose_name': 'Application Camera Link',
                'verbose_name_plural': 'Application Camera Links',
                'unique_together': {('application', 'camera')},
            },
        ),
    ]
