# Generated by Django 5.2.7 on 2025-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='publish',
            field=models.BooleanField(default=False, help_text='If true, this application is visible to the public'),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, help_text='Current firmware version running on the device', max_length=50, null=True),
        ),
    ]
