# Generated by Django 5.2.7 on 2025-11-01 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_application_publish_device_firmware_version'),
        ('Cameras', '0002_camera_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationhascamera',
            name='order',
        ),
        migrations.AlterField(
            model_name='applicationhascamera',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_links', to='Cameras.camera'),
        ),
    ]
