# Generated by Django 5.2.7 on 2025-11-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_remove_applicationhascamera_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
