# Generated by Django 5.2.7 on 2025-11-03 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(help_text='Unique hardware ID (e.g., MAC, UUID, or Serial)', max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('protocol', models.CharField(default='websocket', help_text='Communication protocol used (currently supports WebSocket)', max_length=20)),
                ('device_token', models.CharField(editable=False, help_text='Random token generated for WebSocket authentication', max_length=64, unique=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Firmware version running on the device', max_length=50, null=True)),
                ('payload', models.JSONField(default=dict, help_text="Dynamic JSON structure with nested data, explicit 'type' and 'value'")),
                ('development_enabled', models.BooleanField(default=False, help_text='If True, dashboard/dev tools are enabled for this device')),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_payload_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Applications.application')),
            ],
        ),
    ]
