# Generated by Django 5.2.7 on 2025-11-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0005_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='http_url',
            field=models.URLField(blank=True, help_text='Auto-generated endpoint for REST API', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='websocket_url',
            field=models.URLField(blank=True, help_text='WebSocket endpoint (to be added later)', max_length=300, null=True),
        ),
    ]
