# Generated by Django 5.2.7 on 2025-12-10 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0006_device_http_url_device_websocket_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='Applications.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_key', models.CharField(help_text='Unique key per dashboard (e.g., w1, w2...)', max_length=50)),
                ('widget_type', models.CharField(help_text='chart | gauge | switch | logs | table | camera | custom', max_length=50)),
                ('subscription_path', models.CharField(help_text='Path to subscribe (parent-level, e.g., Sensors)', max_length=300)),
                ('data_path', models.CharField(help_text='Exact value path to read (e.g., Sensors/temperature)', max_length=300)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Static settings like units, labels, colors')),
                ('layout', models.JSONField(default=dict, help_text='{x, y, w, h}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='Applications.dashboard')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='Applications.device')),
            ],
            options={
                'unique_together': {('dashboard', 'widget_key')},
            },
        ),
    ]
