# Generated by Django 5.2.7 on 2025-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0007_dashboard_dashboardwidget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='theme',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='layout_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
