# Generated by Django 5.2.7 on 2025-12-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_remove_dashboard_is_active_remove_dashboard_settings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='field_type',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='widget_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='data_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.device'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='layout',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='config',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='subscription_path',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='widget_key',
        ),
    ]
