# Generated by Django 5.2.7 on 2025-12-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0009_alter_dashboardwidget_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='device',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardWidget',
        ),
    ]
