# Generated by Django 5.2.7 on 2025-12-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0011_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
