# Generated by Django 5.2.7 on 2025-12-12 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0013_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name within a dashboard (used internally)', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Display title shown in UI', max_length=150, null=True)),
                ('component_type', models.CharField(help_text='number | gauge | graph | switch | logs | custom', max_length=50)),
                ('payload_path', models.CharField(help_text='Device payload path (ex: sensors/temp)', max_length=300)),
                ('value_type', models.CharField(default='auto', help_text='auto | int | float | boolean | string', max_length=20)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('ui_config', models.JSONField(default=dict, help_text='UI specific config (colors, limits, labels, etc.)')),
                ('layout', models.JSONField(default=dict, help_text='Grid layout: {x, y, w, h}')),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional ordering inside dashboard')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Applications.dashboard')),
                ('device', models.ForeignKey(blank=True, help_text='Device this component is bound to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_components', to='Applications.device')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('dashboard', 'name')},
            },
        ),
    ]
