# Generated by Django 5.2.7 on 2025-12-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0014_dashboardcomponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardComponent',
        ),
    ]
