# Generated by Django 5.2.7 on 2025-12-19 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0015_delete_dashboardcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(help_text='Internal unique widget name (used in APIs, immutable)', max_length=100)),
                ('title', models.CharField(help_text='Display title shown in UI', max_length=150)),
                ('hide_title', models.BooleanField(default=False, help_text='Whether to hide widget title in dashboard')),
                ('widget_type', models.CharField(help_text='simple_card | gauge | graph | logs | switch | table | custom', max_length=50)),
                ('data_mode', models.CharField(default='realtime', help_text='realtime | historical', max_length=20)),
                ('payload_path', models.CharField(help_text='Device payload path (ex: sensors/temp)', max_length=300)),
                ('value_type', models.CharField(default='auto', help_text='auto | int | float | boolean | string', max_length=20)),
                ('query_config', models.JSONField(default=dict, help_text="\n        Data query behavior:\n        {\n          time_range: {...},\n          aggregation: AVG|SUM|MIN|MAX|LAST,\n          unit: '°C',\n          decimals: 2,\n          sampling: raw|minute|hour\n        }\n        ")),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('ui_config', models.JSONField(default=dict, help_text='\n        UI only:\n        {\n          color,\n          thresholds,\n          graph_style,\n          icon,\n          show_unit\n        }\n        ')),
                ('layout', models.JSONField(default=dict, help_text='Grid layout: {x, y, w, h}')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Applications.dashboard')),
                ('device', models.ForeignKey(blank=True, help_text='Device this widget is bound to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_components', to='Applications.device')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('dashboard', 'widget_name')},
            },
        ),
    ]
