# Generated by Django 5.2.7 on 2026-01-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0016_dashboardcomponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardComponent',
        ),
    ]
