# Generated by Django 5.2.7 on 2026-01-06 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0017_delete_dashboardcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(help_text='Internal unique widget identifier (immutable)', max_length=100)),
                ('widget_type', models.CharField(help_text='simple_card | gauge | comparison | graph | switch | custom', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Render order in dashboard')),
                ('config', models.JSONField(default=dict, help_text='\n        Complete widget configuration.\n        Frontend-controlled.\n\n        Example:\n        {\n          "title": "Engine Temperature",\n          "hide_title": false,\n\n          "bindings": [\n            {\n              "device_id": 20,\n              "payload_path": "sensors/temp",\n              "label": "Engine 1"\n            }\n          ],\n\n          "static": {\n            "unit": "°C",\n            "min": 0,\n            "max": 300\n          },\n\n          "ui": {\n            "icon": "thermometer",\n            "color": "orange"\n          }\n        }\n        ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Applications.dashboard')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('dashboard', 'widget_name')},
            },
        ),
    ]
