# Generated by Django 5.2.7 on 2026-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0018_dashboardcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_image',
            field=models.ImageField(blank=True, null=True, upload_to='application/images/'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_image_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='spline_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='spline_url_enable',
            field=models.BooleanField(default=False),
        ),
    ]
