# Generated by Django 5.2.7 on 2026-05-19 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0019_application_application_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Parent path the entry was POSTed under, e.g. 'logs/error'", max_length=512)),
                ('key', models.CharField(help_text='Auto-generated child key (-XXXX...) or client-supplied id.', max_length=64)),
                ('data', models.JSONField(help_text='The full body of the POSTed entry (excluding the auto-key).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Applications.device')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['device', 'path', '-created_at'], name='devevt_dev_path_ctime_idx'), models.Index(fields=['device', '-created_at'], name='devevt_dev_ctime_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'path', 'key'), name='devevt_unique_dev_path_key')],
            },
        ),
    ]
