# Generated by Django 5.2.7 on 2026-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0020_deviceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='theme',
            field=models.CharField(default='peach', max_length=32),
        ),
    ]
