# Generated by Django 5.2.7 on 2026-06-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0023_dashboard_publish_desktop_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='public_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
