# Generated by Django 5.2.7 on 2026-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0024_application_public_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='spline_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='spline_url_enable',
            field=models.BooleanField(default=False),
        ),
    ]
