# Generated by Django 5.2.7 on 2026-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0025_application_spline_url_application_spline_url_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='queue_control_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='queue_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
