# Generated by Django 5.2.6 on 2026-06-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0027_companyinformation_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], default='new', max_length=20),
        ),
    ]
