# Generated by Django 5.2.7 on 2026-06-15 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0028_alter_contactsubmission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('count', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='Applications.application')),
            ],
            options={
                'verbose_name': 'Application Daily View',
                'verbose_name_plural': 'Application Daily Views',
                'ordering': ['-date'],
                'unique_together': {('application', 'date')},
            },
        ),
    ]
