# Generated by Django 5.2.7 on 2026-06-15 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0029_applicationdailyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('application', 'Application'), ('dashboard', 'Dashboard'), ('device', 'Device'), ('camera', 'Camera'), ('user', 'User'), ('role', 'Role'), ('company', 'Company'), ('ssl', 'SSL'), ('system', 'System')], db_index=True, max_length=24)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=16)),
                ('entity_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
