"""
Django settings for kiosk_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (project root → backend/kiosk_backend/.env) before reading settings.
# Optional: if python-dotenv isn't installed, env vars must come from the shell.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer a real secret on the server via DJANGO_SECRET_KEY env var.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-m8j2g(012hvvj&yb=4tc5y2(fjuffua6p!nnw5!^e7^kpr1+jc',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Flip via env on the server (DJANGO_DEBUG=false).
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

# Hosts allowed to serve this backend. The server's public IP needs to
# be in this list so Django doesn't refuse the request with
# `DisallowedHost`. '*' is fine while behind a trusted proxy / locked
# down by the firewall.
ALLOWED_HOSTS = [
    '192.210.241.34',
    'localhost',
    '127.0.0.1',
    '*',
]

# Origins allowed to make POST/PUT/PATCH/DELETE that include cookies
# or CSRF tokens. Must include the scheme. Add both http and https
# entries if you'll eventually serve over TLS.
CSRF_TRUSTED_ORIGINS = [
    'http://192.210.241.34',
    'http://192.210.241.34:80',
    'http://192.210.241.34:5173',  # vite dev preview, if you ever run it on the box
    'http://192.210.241.34:8001',
    'https://kiosk-backend.myaccess.cloud',
]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'UserAccounts',
    'Cameras',
    'Applications',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kiosk_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'kiosk_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kiosk_db',
        'USER': 'admin',
        'PASSWORD': 'admin123',
        'HOST': '38.242.216.156', 
        'PORT': '5437',
    }
}

MEDIAMTX_SERVER = {
    "subdomain": "cam.myaccess.cloud",
    "host": "72.60.221.158",           # Replace with your MediaMTX server IP
    "username": "root",              # SSH user
    "password": "Myaccess@2021",  # Or use key-based auth
    "config_path": "/root/projects/mediamtx/mediamtx.yml",
    "docker_container": "mediamtx-server",
    "api_port": 9997,               # default MediaMTX API port
    "api_user": "admin",            # API username
    "api_pass": "admin"          # API password

}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = "/root/projects/kiosk_backend/backend/kiosk_backend/staticfiles"

MEDIA_URL = "/media/"
# Resolve under BASE_DIR so the same setting works on Windows dev + Linux
# deployment without manual tweaking. Override via env if a different
# mount-point is needed in production.
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT") or (BASE_DIR / "media")


FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=144000),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'kiosk_backend.pagination.KioskPageNumberPagination',
    'PAGE_SIZE': 10,
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["redis://:Myaccess2021@178.16.137.196:6379"],
        },
    },
}

AUTH_USER_MODEL = 'UserAccounts.User'

# CORS — for an open dashboard reachable from any browser we leave
# this permissive. Lock down to a specific origin list later by
# setting CORS_ALLOW_ALL_ORIGINS=False and listing CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://192.210.241.34',
    'http://192.210.241.34:80',
    'http://192.210.241.34:5173',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================
# Email — used for password-reset links
# ------------------------------------------------------------
# When EMAIL_HOST_USER + EMAIL_HOST_PASSWORD are set in the env (.env), we
# send via real SMTP (default: Gmail). Otherwise we fall back to Django's
# console backend, which prints the message to the Daphne log instead of
# sending it — handy in dev when you don't want to wire up Gmail yet.
# ============================================================
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'noreply@myaccess.io',
)

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Public URL of the React app — used to build clickable reset links.
# Override on the server via FRONTEND_URL=http://192.210.241.34 (or
# the public hostname once DNS is wired up).
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://192.210.241.34').rstrip('/')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
