"""
Django settings for kiosk_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------
# Environment selection — one switch picks dev vs prod values/keys.
# ------------------------------------------------------------------
#   DJANGO_PRODUCTION=True  -> load .env.production  (production values)
#   DJANGO_PRODUCTION=False -> load .env.development (development values) [default]
# Set DJANGO_PRODUCTION=True in the OS env (systemd / shell) on the
# server, or flip the default below.
PRODUCTION = os.environ.get('DJANGO_PRODUCTION', 'False').strip().lower() in (
    'true', '1', 'yes', 'on',
)

# Load the matching env file before reading any settings. load_dotenv does
# NOT override variables already set in the real OS environment, so the
# shell/systemd always wins; a plain `.env` (if present) fills any gaps.
# Optional: if python-dotenv isn't installed, env vars must come from the shell.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ('.env.production' if PRODUCTION else '.env.development'))
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer a real secret on the server via DJANGO_SECRET_KEY env var.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-m8j2g(012hvvj&yb=4tc5y2(fjuffua6p!nnw5!^e7^kpr1+jc',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to off in production, on in development; override with DJANGO_DEBUG.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False' if PRODUCTION else 'True').strip().lower() in (
    'true', '1', 'yes', 'on',
)

# Hosts allowed to serve this backend. Comma-separated list via
# DJANGO_ALLOWED_HOSTS. '*' is acceptable while behind a trusted reverse
# proxy / locked down by the firewall.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,*').split(',')
    if h.strip()
]

# Origins allowed to make POST/PUT/PATCH/DELETE that include cookies or
# CSRF tokens. Comma-separated list via DJANGO_CSRF_TRUSTED_ORIGINS — each
# entry MUST include the scheme (e.g. https://host, https://host:8001).
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'UserAccounts',
    'Cameras',
    'Applications',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Stashes the current request so activity-log signals can attribute the actor.
    'Applications.current_request.CurrentRequestMiddleware',
]

ROOT_URLCONF = 'kiosk_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'kiosk_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'kiosk_development_db'),
        'USER': os.environ.get('DB_USER', 'kiosk'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'kiosk'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

MEDIAMTX_SERVER = {
    "subdomain": os.environ.get('MEDIAMTX_SUBDOMAIN', 'cam.myaccess.cloud'),
    "host": os.environ.get('MEDIAMTX_HOST', '72.60.221.158'),
    "username": os.environ.get('MEDIAMTX_SSH_USER', 'root'),
    "password": os.environ.get('MEDIAMTX_SSH_PASSWORD', ''),
    "config_path": os.environ.get('MEDIAMTX_CONFIG_PATH', '/root/projects/mediamtx/mediamtx.yml'),
    "docker_container": os.environ.get('MEDIAMTX_CONTAINER', 'mediamtx-server'),
    "api_port": int(os.environ.get('MEDIAMTX_API_PORT', '9997')),
    "api_user": os.environ.get('MEDIAMTX_API_USER', 'admin'),
    "api_pass": os.environ.get('MEDIAMTX_API_PASS', 'admin'),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('DJANGO_STATIC_URL', 'static/')
# Where `collectstatic` gathers files for WhiteNoise to serve. Set
# DJANGO_STATIC_ROOT to collect to a path outside the project; leave it
# blank to use <project>/staticfiles (works on Windows dev + Linux).
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT') or (BASE_DIR / 'staticfiles')

MEDIA_URL = os.environ.get('DJANGO_MEDIA_URL', '/media/')
# Set DJANGO_MEDIA_ROOT to store uploads at a fixed mount-point; leave it
# blank to use <project>/media.
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT') or (BASE_DIR / 'media')


FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=144000),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'kiosk_backend.pagination.KioskPageNumberPagination',
    'PAGE_SIZE': 10,
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Local Redis (low-latency). Override with the REDIS_URL env var to
            # point at a remote/managed instance in other environments.
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")],
        },
    },
}

AUTH_USER_MODEL = 'UserAccounts.User'

# CORS — for an open dashboard reachable from any browser we leave
# this permissive by default. Lock down by setting CORS_ALLOW_ALL_ORIGINS=false
# and listing real origins in DJANGO_CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True').strip().lower() in (
    'true', '1', 'yes', 'on',
)
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'True').strip().lower() in (
    'true', '1', 'yes', 'on',
)
# Used only when CORS_ALLOW_ALL_ORIGINS is False. Comma-separated list via
# DJANGO_CORS_ALLOWED_ORIGINS (include the scheme); falls back to the CSRF list.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', '').split(',')
    if o.strip()
] or CSRF_TRUSTED_ORIGINS

# ============================================================
# Email — used for password-reset links
# ------------------------------------------------------------
# When EMAIL_HOST_USER + EMAIL_HOST_PASSWORD are set in the env (.env), we
# send via real SMTP (default: Gmail). Otherwise we fall back to Django's
# console backend, which prints the message to the Daphne log instead of
# sending it — handy in dev when you don't want to wire up Gmail yet.
# ============================================================
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'noreply@myaccess.io',
)

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Public URL of the React app — used to build clickable reset links.
# Override on the server via FRONTEND_URL=http://192.210.241.34 (or
# the public hostname once DNS is wired up).
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://192.210.241.34').rstrip('/')
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ------------------------------------------------------------------
# Production-only hardening (behind an HTTPS reverse proxy like nginx)
# ------------------------------------------------------------------
if PRODUCTION:
    # Trust nginx's X-Forwarded-Proto header so Django knows the original
    # request was HTTPS — required for correct CSRF checks & secure cookies.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
