# Generated by Django 5.2.7 on 2025-10-31 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.CharField(choices=[('rtsp', 'RTSP'), ('webrtc', 'WebRTC'), ('onvif', 'ONVIF'), ('http', 'HTTP'), ('other', 'Other')], max_length=20)),
                ('url', models.TextField(help_text='Camera stream URL (RTSP or WebRTC)')),
                ('stream_path', models.CharField(help_text='Stream alias used in MediaMTX (e.g., cam1, kiosk_front)', max_length=100, unique=True)),
                ('webrtc_url', models.TextField(blank=True, help_text='Complete WebRTC playback URL (e.g., https://stream.domain.com/cam1/whep)', null=True)),
                ('status', models.BooleanField(default=False, help_text='True if camera is reachable')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this camera')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
