# Generated by Django 5.2.7 on 2025-11-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='viewers',
            field=models.PositiveIntegerField(default=0, help_text='Active viewer count'),
        ),
    ]
