/* =====================================================================
   Country dial codes + national mobile-number length ranges.

   Each entry: { code: ISO-3166 alpha-2, name, dial, min, max }
   where `min`/`max` are the number of digits in the NATIONAL number
   (i.e. excluding the dial code). Used by the Add/Edit User form to:
     • render the country-code dropdown, and
     • cap / validate the mobile number length per selected country.

   Lengths follow ITU / libphonenumber conventions for mobile numbers.
   For a handful of countries with wide variance a sensible range is used.
   ===================================================================== */

export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', dial: '+93', min: 9, max: 9 },
  { code: 'AL', name: 'Albania', dial: '+355', min: 9, max: 9 },
  { code: 'DZ', name: 'Algeria', dial: '+213', min: 9, max: 9 },
  { code: 'AD', name: 'Andorra', dial: '+376', min: 6, max: 6 },
  { code: 'AO', name: 'Angola', dial: '+244', min: 9, max: 9 },
  { code: 'AR', name: 'Argentina', dial: '+54', min: 10, max: 11 },
  { code: 'AM', name: 'Armenia', dial: '+374', min: 8, max: 8 },
  { code: 'AU', name: 'Australia', dial: '+61', min: 9, max: 9 },
  { code: 'AT', name: 'Austria', dial: '+43', min: 10, max: 11 },
  { code: 'AZ', name: 'Azerbaijan', dial: '+994', min: 9, max: 9 },
  { code: 'BH', name: 'Bahrain', dial: '+973', min: 8, max: 8 },
  { code: 'BD', name: 'Bangladesh', dial: '+880', min: 10, max: 10 },
  { code: 'BY', name: 'Belarus', dial: '+375', min: 9, max: 9 },
  { code: 'BE', name: 'Belgium', dial: '+32', min: 9, max: 9 },
  { code: 'BZ', name: 'Belize', dial: '+501', min: 7, max: 7 },
  { code: 'BJ', name: 'Benin', dial: '+229', min: 8, max: 8 },
  { code: 'BT', name: 'Bhutan', dial: '+975', min: 8, max: 8 },
  { code: 'BO', name: 'Bolivia', dial: '+591', min: 8, max: 8 },
  { code: 'BA', name: 'Bosnia and Herzegovina', dial: '+387', min: 8, max: 8 },
  { code: 'BW', name: 'Botswana', dial: '+267', min: 8, max: 8 },
  { code: 'BR', name: 'Brazil', dial: '+55', min: 10, max: 11 },
  { code: 'BN', name: 'Brunei', dial: '+673', min: 7, max: 7 },
  { code: 'BG', name: 'Bulgaria', dial: '+359', min: 8, max: 9 },
  { code: 'BF', name: 'Burkina Faso', dial: '+226', min: 8, max: 8 },
  { code: 'BI', name: 'Burundi', dial: '+257', min: 8, max: 8 },
  { code: 'KH', name: 'Cambodia', dial: '+855', min: 8, max: 9 },
  { code: 'CM', name: 'Cameroon', dial: '+237', min: 9, max: 9 },
  { code: 'CA', name: 'Canada', dial: '+1', min: 10, max: 10 },
  { code: 'CV', name: 'Cape Verde', dial: '+238', min: 7, max: 7 },
  { code: 'CF', name: 'Central African Republic', dial: '+236', min: 8, max: 8 },
  { code: 'TD', name: 'Chad', dial: '+235', min: 8, max: 8 },
  { code: 'CL', name: 'Chile', dial: '+56', min: 9, max: 9 },
  { code: 'CN', name: 'China', dial: '+86', min: 11, max: 11 },
  { code: 'CO', name: 'Colombia', dial: '+57', min: 10, max: 10 },
  { code: 'KM', name: 'Comoros', dial: '+269', min: 7, max: 7 },
  { code: 'CG', name: 'Congo', dial: '+242', min: 9, max: 9 },
  { code: 'CD', name: 'Congo (DRC)', dial: '+243', min: 9, max: 9 },
  { code: 'CR', name: 'Costa Rica', dial: '+506', min: 8, max: 8 },
  { code: 'CI', name: "Côte d'Ivoire", dial: '+225', min: 10, max: 10 },
  { code: 'HR', name: 'Croatia', dial: '+385', min: 8, max: 9 },
  { code: 'CU', name: 'Cuba', dial: '+53', min: 8, max: 8 },
  { code: 'CY', name: 'Cyprus', dial: '+357', min: 8, max: 8 },
  { code: 'CZ', name: 'Czechia', dial: '+420', min: 9, max: 9 },
  { code: 'DK', name: 'Denmark', dial: '+45', min: 8, max: 8 },
  { code: 'DJ', name: 'Djibouti', dial: '+253', min: 8, max: 8 },
  { code: 'DO', name: 'Dominican Republic', dial: '+1', min: 10, max: 10 },
  { code: 'EC', name: 'Ecuador', dial: '+593', min: 9, max: 9 },
  { code: 'EG', name: 'Egypt', dial: '+20', min: 10, max: 10 },
  { code: 'SV', name: 'El Salvador', dial: '+503', min: 8, max: 8 },
  { code: 'GQ', name: 'Equatorial Guinea', dial: '+240', min: 9, max: 9 },
  { code: 'ER', name: 'Eritrea', dial: '+291', min: 7, max: 7 },
  { code: 'EE', name: 'Estonia', dial: '+372', min: 7, max: 8 },
  { code: 'SZ', name: 'Eswatini', dial: '+268', min: 8, max: 8 },
  { code: 'ET', name: 'Ethiopia', dial: '+251', min: 9, max: 9 },
  { code: 'FJ', name: 'Fiji', dial: '+679', min: 7, max: 7 },
  { code: 'FI', name: 'Finland', dial: '+358', min: 9, max: 10 },
  { code: 'FR', name: 'France', dial: '+33', min: 9, max: 9 },
  { code: 'GA', name: 'Gabon', dial: '+241', min: 7, max: 8 },
  { code: 'GM', name: 'Gambia', dial: '+220', min: 7, max: 7 },
  { code: 'GE', name: 'Georgia', dial: '+995', min: 9, max: 9 },
  { code: 'DE', name: 'Germany', dial: '+49', min: 10, max: 11 },
  { code: 'GH', name: 'Ghana', dial: '+233', min: 9, max: 9 },
  { code: 'GR', name: 'Greece', dial: '+30', min: 10, max: 10 },
  { code: 'GT', name: 'Guatemala', dial: '+502', min: 8, max: 8 },
  { code: 'GN', name: 'Guinea', dial: '+224', min: 9, max: 9 },
  { code: 'GY', name: 'Guyana', dial: '+592', min: 7, max: 7 },
  { code: 'HT', name: 'Haiti', dial: '+509', min: 8, max: 8 },
  { code: 'HN', name: 'Honduras', dial: '+504', min: 8, max: 8 },
  { code: 'HK', name: 'Hong Kong', dial: '+852', min: 8, max: 8 },
  { code: 'HU', name: 'Hungary', dial: '+36', min: 9, max: 9 },
  { code: 'IS', name: 'Iceland', dial: '+354', min: 7, max: 7 },
  { code: 'IN', name: 'India', dial: '+91', min: 10, max: 10 },
  { code: 'ID', name: 'Indonesia', dial: '+62', min: 9, max: 11 },
  { code: 'IR', name: 'Iran', dial: '+98', min: 10, max: 10 },
  { code: 'IQ', name: 'Iraq', dial: '+964', min: 10, max: 10 },
  { code: 'IE', name: 'Ireland', dial: '+353', min: 9, max: 9 },
  { code: 'IL', name: 'Israel', dial: '+972', min: 9, max: 9 },
  { code: 'IT', name: 'Italy', dial: '+39', min: 9, max: 10 },
  { code: 'JM', name: 'Jamaica', dial: '+1', min: 10, max: 10 },
  { code: 'JP', name: 'Japan', dial: '+81', min: 10, max: 10 },
  { code: 'JO', name: 'Jordan', dial: '+962', min: 9, max: 9 },
  { code: 'KZ', name: 'Kazakhstan', dial: '+7', min: 10, max: 10 },
  { code: 'KE', name: 'Kenya', dial: '+254', min: 9, max: 9 },
  { code: 'KW', name: 'Kuwait', dial: '+965', min: 8, max: 8 },
  { code: 'KG', name: 'Kyrgyzstan', dial: '+996', min: 9, max: 9 },
  { code: 'LA', name: 'Laos', dial: '+856', min: 8, max: 10 },
  { code: 'LV', name: 'Latvia', dial: '+371', min: 8, max: 8 },
  { code: 'LB', name: 'Lebanon', dial: '+961', min: 7, max: 8 },
  { code: 'LS', name: 'Lesotho', dial: '+266', min: 8, max: 8 },
  { code: 'LR', name: 'Liberia', dial: '+231', min: 7, max: 9 },
  { code: 'LY', name: 'Libya', dial: '+218', min: 9, max: 9 },
  { code: 'LI', name: 'Liechtenstein', dial: '+423', min: 7, max: 7 },
  { code: 'LT', name: 'Lithuania', dial: '+370', min: 8, max: 8 },
  { code: 'LU', name: 'Luxembourg', dial: '+352', min: 9, max: 9 },
  { code: 'MO', name: 'Macau', dial: '+853', min: 8, max: 8 },
  { code: 'MG', name: 'Madagascar', dial: '+261', min: 9, max: 9 },
  { code: 'MW', name: 'Malawi', dial: '+265', min: 9, max: 9 },
  { code: 'MY', name: 'Malaysia', dial: '+60', min: 9, max: 10 },
  { code: 'MV', name: 'Maldives', dial: '+960', min: 7, max: 7 },
  { code: 'ML', name: 'Mali', dial: '+223', min: 8, max: 8 },
  { code: 'MT', name: 'Malta', dial: '+356', min: 8, max: 8 },
  { code: 'MR', name: 'Mauritania', dial: '+222', min: 8, max: 8 },
  { code: 'MU', name: 'Mauritius', dial: '+230', min: 8, max: 8 },
  { code: 'MX', name: 'Mexico', dial: '+52', min: 10, max: 10 },
  { code: 'MD', name: 'Moldova', dial: '+373', min: 8, max: 8 },
  { code: 'MC', name: 'Monaco', dial: '+377', min: 8, max: 9 },
  { code: 'MN', name: 'Mongolia', dial: '+976', min: 8, max: 8 },
  { code: 'ME', name: 'Montenegro', dial: '+382', min: 8, max: 8 },
  { code: 'MA', name: 'Morocco', dial: '+212', min: 9, max: 9 },
  { code: 'MZ', name: 'Mozambique', dial: '+258', min: 9, max: 9 },
  { code: 'MM', name: 'Myanmar', dial: '+95', min: 8, max: 10 },
  { code: 'NA', name: 'Namibia', dial: '+264', min: 9, max: 9 },
  { code: 'NP', name: 'Nepal', dial: '+977', min: 10, max: 10 },
  { code: 'NL', name: 'Netherlands', dial: '+31', min: 9, max: 9 },
  { code: 'NZ', name: 'New Zealand', dial: '+64', min: 8, max: 10 },
  { code: 'NI', name: 'Nicaragua', dial: '+505', min: 8, max: 8 },
  { code: 'NE', name: 'Niger', dial: '+227', min: 8, max: 8 },
  { code: 'NG', name: 'Nigeria', dial: '+234', min: 10, max: 10 },
  { code: 'KP', name: 'North Korea', dial: '+850', min: 8, max: 10 },
  { code: 'MK', name: 'North Macedonia', dial: '+389', min: 8, max: 8 },
  { code: 'NO', name: 'Norway', dial: '+47', min: 8, max: 8 },
  { code: 'OM', name: 'Oman', dial: '+968', min: 8, max: 8 },
  { code: 'PK', name: 'Pakistan', dial: '+92', min: 10, max: 10 },
  { code: 'PS', name: 'Palestine', dial: '+970', min: 9, max: 9 },
  { code: 'PA', name: 'Panama', dial: '+507', min: 8, max: 8 },
  { code: 'PG', name: 'Papua New Guinea', dial: '+675', min: 8, max: 8 },
  { code: 'PY', name: 'Paraguay', dial: '+595', min: 9, max: 9 },
  { code: 'PE', name: 'Peru', dial: '+51', min: 9, max: 9 },
  { code: 'PH', name: 'Philippines', dial: '+63', min: 10, max: 10 },
  { code: 'PL', name: 'Poland', dial: '+48', min: 9, max: 9 },
  { code: 'PT', name: 'Portugal', dial: '+351', min: 9, max: 9 },
  { code: 'QA', name: 'Qatar', dial: '+974', min: 8, max: 8 },
  { code: 'RO', name: 'Romania', dial: '+40', min: 9, max: 9 },
  { code: 'RU', name: 'Russia', dial: '+7', min: 10, max: 10 },
  { code: 'RW', name: 'Rwanda', dial: '+250', min: 9, max: 9 },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966', min: 9, max: 9 },
  { code: 'SN', name: 'Senegal', dial: '+221', min: 9, max: 9 },
  { code: 'RS', name: 'Serbia', dial: '+381', min: 8, max: 9 },
  { code: 'SC', name: 'Seychelles', dial: '+248', min: 7, max: 7 },
  { code: 'SL', name: 'Sierra Leone', dial: '+232', min: 8, max: 8 },
  { code: 'SG', name: 'Singapore', dial: '+65', min: 8, max: 8 },
  { code: 'SK', name: 'Slovakia', dial: '+421', min: 9, max: 9 },
  { code: 'SI', name: 'Slovenia', dial: '+386', min: 8, max: 8 },
  { code: 'SO', name: 'Somalia', dial: '+252', min: 8, max: 9 },
  { code: 'ZA', name: 'South Africa', dial: '+27', min: 9, max: 9 },
  { code: 'KR', name: 'South Korea', dial: '+82', min: 9, max: 10 },
  { code: 'SS', name: 'South Sudan', dial: '+211', min: 9, max: 9 },
  { code: 'ES', name: 'Spain', dial: '+34', min: 9, max: 9 },
  { code: 'LK', name: 'Sri Lanka', dial: '+94', min: 9, max: 9 },
  { code: 'SD', name: 'Sudan', dial: '+249', min: 9, max: 9 },
  { code: 'SE', name: 'Sweden', dial: '+46', min: 7, max: 10 },
  { code: 'CH', name: 'Switzerland', dial: '+41', min: 9, max: 9 },
  { code: 'SY', name: 'Syria', dial: '+963', min: 9, max: 9 },
  { code: 'TW', name: 'Taiwan', dial: '+886', min: 9, max: 9 },
  { code: 'TJ', name: 'Tajikistan', dial: '+992', min: 9, max: 9 },
  { code: 'TZ', name: 'Tanzania', dial: '+255', min: 9, max: 9 },
  { code: 'TH', name: 'Thailand', dial: '+66', min: 9, max: 9 },
  { code: 'TG', name: 'Togo', dial: '+228', min: 8, max: 8 },
  { code: 'TN', name: 'Tunisia', dial: '+216', min: 8, max: 8 },
  { code: 'TR', name: 'Turkey', dial: '+90', min: 10, max: 10 },
  { code: 'TM', name: 'Turkmenistan', dial: '+993', min: 8, max: 8 },
  { code: 'UG', name: 'Uganda', dial: '+256', min: 9, max: 9 },
  { code: 'UA', name: 'Ukraine', dial: '+380', min: 9, max: 9 },
  { code: 'AE', name: 'United Arab Emirates', dial: '+971', min: 9, max: 9 },
  { code: 'GB', name: 'United Kingdom', dial: '+44', min: 10, max: 10 },
  { code: 'US', name: 'United States', dial: '+1', min: 10, max: 10 },
  { code: 'UY', name: 'Uruguay', dial: '+598', min: 8, max: 8 },
  { code: 'UZ', name: 'Uzbekistan', dial: '+998', min: 9, max: 9 },
  { code: 'VE', name: 'Venezuela', dial: '+58', min: 10, max: 10 },
  { code: 'VN', name: 'Vietnam', dial: '+84', min: 9, max: 10 },
  { code: 'YE', name: 'Yemen', dial: '+967', min: 9, max: 9 },
  { code: 'ZM', name: 'Zambia', dial: '+260', min: 9, max: 9 },
  { code: 'ZW', name: 'Zimbabwe', dial: '+263', min: 9, max: 9 },
]

/** Unicode flag emoji from an ISO-3166 alpha-2 code (e.g. "IN" → 🇮🇳). */
export function flagOf(code) {
  if (!code || code.length !== 2) return '🏳️'
  const A = 0x1f1e6
  return String.fromCodePoint(A + code.charCodeAt(0) - 65, A + code.charCodeAt(1) - 65)
}

/** Look up a country by ISO-3166 alpha-2 code. */
export function countryByCode(code) {
  return COUNTRIES.find((c) => c.code === code) || null
}

/** First country matching a dial code (e.g. "+1" → United States). */
export function countryByDial(dial) {
  if (!dial) return null
  const d = String(dial).trim()
  const norm = d.startsWith('+') ? d : '+' + d
  return COUNTRIES.find((c) => c.dial === norm) || null
}
